def get_odap(sar_filename):
    """ Add docstring"""
    ... code to get date etc ...
    ... code to construct odap urls / code to search csw and extract odap urls ...
    return norkyst_url, met_nordic_url
